# common CMake file for the paths for all of the projects

if(WIN32)

	if(${PLATFORM} STREQUAL "Laptop")
		set(COMMON_ROOT "D:/Common")
        set(RYML_ROOT "D:/Projects/rapidyaml")
        set(MIXER_ROOT "D:/Projects/mixer")
	elseif(${PLATFORM} STREQUAL "LaptopN")
		set(COMMON_ROOT "C:/Projects/Common")
        set(RYML_ROOT "C:/Projects/rapidyaml")
        set(MIXER_ROOT "C:/Projects/mixer")
    elseif(${PLATFORM} STREQUAL "BEAST")
        set(COMMON_ROOT "D:/Projects/Common")
        set(RYML_ROOT "D:/Projects/rapidyaml")
        set(MIXER_ROOT "D:/Projects/mixer")
    elseif(${PLATFORM} STREQUAL "Laptop_Beast")
        set(COMMON_ROOT "D:/Projects/Common")
        set(RYML_ROOT "D:/Projects/rapidyaml")
        set(MIXER_ROOT "D:/Projects/mixer")    
    else()
        set(COMMON_ROOT "C:/Projects/Common")
        set(RYML_ROOT "C:/Projects/rapidyaml")
        set(MIXER_ROOT "C:/Projects/mixer")
    endif()    
    
else()

    if(${PLATFORM} STREQUAL "MainGear")
        set(_ECLIPSE_VERSION "3.8")
        set(COMMON_ROOT "~/Projects/Common")
        set(RYML_ROOT "~/Projects/rapidyaml")
        set(MIXER_ROOT "~/Projects/mixer")
    elseif(${PLATFORM} STREQUAL "HPC")
        set(COMMON_ROOT "~/Projects/Common")
        set(RYML_ROOT "~/Projects/rapidyaml")
        set(MIXER_ROOT "~/Projects/mixer")
    elseif(${PLATFORM} STREQUAL "WSL")
        set(COMMON_ROOT "../../../Projects/Common")
        set(RYML_ROOT "../../../Projects/rapidyaml")     
        set(MIXER_ROOT "../../../Projects/mixer")
    else()
        set(COMMON_ROOT "~/Projects/Common")
        set(RYML_ROOT "~/Projects/rapidyaml")
        set(MIXER_ROOT "~/Projects/mixer")
    endif()
    
endif()